g_and_s = [
    'Amaranth',
    'Barley',
    'Buckwheat',
    'Bulgur',
    'Corn',
    'Durum Wheat',
    'Farro',
    'Einkorn',
    'Kañiwa',
    'Khorasan Wheat',
    'Millets',
    'Oats',
    'Quinoa',
    'Rice',
    'Rye',
    'Sorghum',
    'Teff',
    'Triticale',
    'Wheat',
    'Wild Rice',
    'Hanza',
    'Chia',
    'Flax',
    'Breadnut',
    'Sesame',
    'Hemp Seed',
    'Poppy Seed',
    'Semolina',
    'Rolled Oats',
    'Cattail',
    'Sunflower Seed',
    'Pumpkin Seed',
    'Watermelon Seed'
]